version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Minit.Api/Dockerfile
    container_name: minit-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=minitdb;Username=postgres;Password=postgres
      Admin__ApiKey: super-secret-admin-key
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17-alpine
    container_name: minit-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: minitdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d minitdb" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
